name: Update WakaTime Stats

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Update WakaTime Stats
        uses: athul/waka-readme@master
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
